spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  h2-console:
    settings:
      web-allow-others: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

file-path:
  company: fake-company-path
  company-analysis: fake-company-analysis-path
  company-growth: fake-company-growth-path
  company-sentiment: fake-company-sentiment-path
  company-news: fake-company-news-path
  company-comparison: fake-company-comparison-path
